export const QUESTIONS = {
  self_awareness: [
    'Can you provide insights about my personality based on my birth chart ?',
    'What are the strengths and weaknesses indicated in my birth chart?',
    'Generate insights about my general demeanor and approach to life based on my ascendant sign',
    'How do the planets housed in my ascendant house impact my personality?',
    'How does my Sun sign contribute to my personality traits?',
    'What insights can you provide about my personality from the planetary positions in different " \
      "houses in my vedic horoscope? ',
    'How do I typically appear to others upon first impression  ?',
    'What are my primary motivations and desires in life  ?',
    'How do I typically respond to new situations and challenges ?',
    'What are my primary motivations and desires in life according to my astrological information ?',
    'How do I typically respond to new situations and challenges according to my astrological information ?',
    'What are my natural strengths and talents according to my astrological information ?',
    'What are the negatives in my horoscope ?',
    'How do I tend to approach relationships and social interactions according to my astrological information ?',
    'How do I express myself creatively and artistically according to my astrological information ?',
    'What are my natural inclinations and preferences in terms of lifestyle and environment according to my astrological information ?',
    'What are my tendencies in terms of self-care and well-being according to my astrological information ?',
    'What steps can I take to enhance my overall well-being and happiness according to my astrological information ?',
  ],
  family: [
    'What does my birth chart suggest about my family dynamics?',
    'How do the planetary positions in my birth chart influence my relationships with family " \
      "members?',
    'Are there any specific planetary placements that indicate challenges or conflicts within my " \
      "family?',
    'Are there any karmic or past-life connections indicated in my birth chart that influence my " \
      "family dynamics? ',
    'What role do the Moon and Venus placements play in shaping my emotional connections and bonds " \
      "with family members?',
    'Are there any astrological remedies or practices I can incorporate to foster harmony and " \
      "unity within my family?',
  ],
  wealth: [
    'Can astrology provide insights into my spending habits and tendencies based on my astrological profile',
    'What career paths or investment opportunities align with my astrological profile',
    'How can I mitigate financial risks and maximize opportunities based on my astrological profile',
    'What steps can I take to manifest abundance and financial success based on my astrological profile',
    'How can I align my financial goals with my life purpose and astrological chart based on my astrological profile',
    'What is my natural inclination towards handling money and finances based on my astrological profile',
    'What areas of my life should I focus on to improve my overall financial well-being based on " \
      "my astrological profile',
    'Are there any planetary placements or aspects that indicate a need for caution in financial matters based on my astrological profile',
    'What role does karma or past-life influences play in shaping my current financial situation based on my astrological profile',
    'Can astrology help me identify the most auspicious timing for major financial decisions or investments?',
  ],
  health: [
    'Can you predict any health issues or concerns in the near future based on my astrological profile?',
    'What sort of health issues will I have according to my astrological profile? ',
    'How can I maintain good physical health based on my birth chart?',
    'Give me 5 strengths and weaknesses related to health based on my astrological profile?',
    'Will I experience emotional stability or fluctuations in mood based on my astrological profile?',
    'Can you suggest coping strategies or therapies for emotional healing based on my astrological profile?',
  ],
  numerology: [
    'What insights can numerology provide about my personality traits, strengths, and weaknesses?',
    'How does my life path number influence the major events and opportunities in my life?',
    'Can numerology help me understand my relationships with others, including family, friends, and romantic partners?',
    'Are there any significant numbers or patterns in my numerology chart that indicate areas of focus or potential challenges?',
    'How can I use numerology to make informed decisions about my career, finances, and personal growth?',
  ],
  travel: [
    'Can you predict any travel opportunities or relocations for me based on my astrological profile?',
    'Can you suggest destinations that align with my astrological profile based on my astrological profile?',
    'How can I ensure safe and enjoyable travels based on my birth chart?',
  ],
  business: [],
  'Who Am I': ['Who Am I'],
  Remedies: [
    'What general remedies should I follow to improve my overall well-being?',
    'Are there any specific rituals or practices I should perform today?',
    'What remedies can help me advance in my career?',
    'What remedies can help improve my financial situation?',
    'What remedies can strengthen my relationship with my partner?',
  ],
  'Job VS Business': [
    'What does my birth chart suggest about my career path? Should I pursue a job or start my own business?',
    'Based on my astrological profile, which is more suitable for me: a stable job in a corporate environment or an entrepreneurial venture?',
    'Are there any specific planetary placements or aspects in my chart that indicate success in business?',
    'What do the positions of my 10th and 7th houses indicate about my potential for career success in a job vs. running a business?',
    'How do the current planetary transits and my dasha period affect my prospects for starting a business?',
    'Are there any yogas or doshas in my chart that could influence my decision to pursue a job or a business?',
    'What do the planets in my 6th and 7th houses suggest about my ability to thrive in a job versus owning a business?',
    'Does my chart indicate any particular fields or industries where I would be more successful in a job or business?',
    'Are there any upcoming favorable periods for making a significant career change, such as starting a business or switching jobs?',
    'Based on my ascendant and the placement of key planets, what are the strengths and challenges I might face in a job versus a business?',
  ],
  Love: [
    'What does my birth chart suggest about my love life and romantic relationships?',
    'Are there any upcoming favorable periods for finding love or improving my current relationship?',
    'What do the positions of Venus and the 7th house in my chart indicate about my love life?',
    'Are there any specific planetary aspects or transits that might affect my romantic relationships?',
    'What astrological remedies can help me attract a loving and compatible partner?',
    'How can I use astrology to heal from a recent breakup and move forward?',
    'What do my moon sign and Venus sign reveal about my emotional needs and love preferences?',
    'Are there any doshas in my chart that might be affecting my love life negatively?',
    'What are the strengths and challenges in my romantic relationships based on my astrological profile?',
    'How can I improve my relationship with my partner using astrological insights?',
  ],
  Students: [
    'What does my birth chart indicate about my academic strengths and weaknesses?',
    'Based on my astrological profile, which subjects or fields of study would be most suitable for me?',
    'How do the positions of Mercury and the 5th house affect my learning and educational pursuits?',
    'Are there any specific planetary aspects or transits that might impact my academic performance?',
    'What astrological remedies can help me excel in my studies and improve my concentration?',
    'Are there any upcoming favorable periods for taking exams or making significant educational decisions?',
    'What do my moon sign and ascendant reveal about my learning style and study habits?',
    'Are there any doshas in my chart that might be affecting my academic success?',
    'How can I use astrology to manage stress and stay motivated in my studies?',
    'What career paths are best suited for me based on my educational interests and astrological profile?',
  ],
  'Foreign Settlement': [
    'Will I have opportunities to settle abroad?',
    'What is the best period for me to move to a foreign country?',
    'Which countries are most favorable for my foreign settlement?',
    'Are there any planetary positions that support foreign travel for me?',
    'Will I find success in my career if I move abroad?',
    'What challenges might I face when settling in a foreign country?',
    'Will I experience cultural adaptation issues in a foreign land?',
    'Is foreign education a good option for me?',
    'How will my financial situation be if I move abroad?',
    'Will my family support my decision to settle abroad?',
    'What impact will foreign settlement have on my personal relationships?',
    'Are there any specific rituals or remedies to enhance my chances of foreign settlement?',
    'Will I find good accommodation and living conditions abroad?',
    'What should I be cautious about when planning to move abroad?',
    'Will I be able to maintain my cultural identity in a foreign country?',
  ],
  'Improving Sex Life': [
    'How does the position of Venus influence my approach to romance and intimacy?',
    'What does Mars indicate about my sexual energy and desires?',
    'Are there any astrological periods that are particularly favorable for enhancing my sexual relationship?',
    "How can the Moon's position help me understand my emotional needs in a sexual relationship?",
    'What can the 5th house reveal about my creative and romantic expressions?',
    'How does the 8th house influence my sexual instincts and transformation through intimacy?',
    'What role does the placement of Saturn play in my sexual life, and how can I overcome any challenges?',
    'How do planetary transits affect my current sexual relationships?',
    'Are there any specific yogas or doshas in my chart that impact my sexual life?',
    'What remedies can improve my sexual energy and intimacy with my partner?',
  ],
  'Career Insights Problems': [
    'What does my birth chart suggest about my career path? Should I focus on advancing in my current job or explore new opportunities?',
    "I'm considering my career options. Based on my astrological profile, which type of work environment would suit me best?",
    'Can you identify specific planetary influences in my chart that impact my job performance and career success?',
    'How do the positions of planets in my chart affect my interactions with colleagues and my work environment?',
    'What strengths and challenges do my chart indicate for my relationships with superiors and colleagues?',
    'Can you provide insights on the current planetary influences and periods? How might they affect my career growth and challenges?',
    'Are there any factors in my chart that could affect my job performance or relationships at work?',
    'How do the positions of Mercury and Venus in my chart influence my communication style and relationships with colleagues and superiors?',
    'Do you see any upcoming favorable periods for career advancement, promotion, or recognition in my current job?',
    'Based on my astrological profile, what strengths and challenges might I encounter in my current job role?',
    'What can you tell me about potential career changes or shifts in my professional life based on my chart?',
    'How can I improve my professional relationships and interactions with colleagues based on astrological insights?',
    'Are there any specific skills or talents indicated in my chart that I should focus on developing for career advancement?',
    'What career obstacles or challenges might I face in the near future according to my astrological chart?',
    'How can I best navigate office politics and challenges in my workplace based on my astrological profile?',
  ],
  'Know your child': [
    'What are the key personality traits of my child according to their astrological chart?',
    "What are the main strengths and weaknesses indicated in my child's astrological chart?",
    "What does my child's astrological chart reveal about their emotional needs and how they express their emotions?",
    "What is my child's preferred learning style according to their astrological chart? How can I best support their education?",
    "What talents and abilities are highlighted in my child's astrological chart? How can I help them develop these talents?",
    'How does my child interact with others? What does their chart say about their social skills and friendships?',
    'What potential challenges or obstacles might my child face according to their astrological chart?',
    "What does my child's astrological chart indicate about their physical and mental health? Are there any areas I should pay particular attention to?",
    "What career paths or aspirations are suggested by my child's astrological chart?",
    'How does my child relate to their parents? What can I do to improve our relationship according to their astrological chart?',
    "What future predictions can be made about my child's life based on their astrological chart?",
    "What does my child's astrological chart reveal about their potential for spiritual and personal growth?",
    'What hobbies and interests are likely to appeal to my child according to their astrological chart?',
    'How does my child prefer to communicate? What does their chart say about their communication style?',
    'How does my child handle conflicts? What strategies can I use to help them resolve conflicts effectively according to their astrological chart?',
  ],
  'Know your husband': [
    'What are the key personality traits of my husband according to his astrological chart?',
    "What are the main strengths and weaknesses indicated in my husband's astrological chart?",
    "What does my husband's astrological chart reveal about his emotional needs and how he expresses his emotions?",
    'How does my husband prefer to communicate? What does his chart say about his communication style?',
    "What career paths or aspirations are suggested by my husband's astrological chart?",
    "What talents and abilities are highlighted in my husband's astrological chart? How can I support him in developing these talents?",
    'How does my husband interact with others? What does his chart say about his social skills and friendships?',
    "What does my husband's astrological chart indicate about our relationship dynamics and compatibility?",
    "What does my husband's astrological chart indicate about his physical and mental health? Are there any areas I should pay particular attention to?",
    'How does my husband handle conflicts? What strategies can we use to resolve conflicts effectively according to his astrological chart?',
    "What does my husband's astrological chart reveal about his financial habits and approach to money management?",
    'What hobbies and interests are likely to appeal to my husband according to his astrological chart?',
    "What does my husband's astrological chart reveal about his potential for spiritual and personal growth?",
    "What future predictions can be made about my husband's life based on his astrological chart?",
    'How does my husband relate to his family? What can his chart tell me about his family dynamics and relationships?',
  ],
  'Know your wife': [
    'What are the key personality traits of my wife according to her astrological chart?',
    "What are the main strengths and weaknesses indicated in my wife's astrological chart?",
    "What does my wife's astrological chart reveal about her emotional needs and how she expresses her emotions?",
    'How does my wife prefer to communicate? What does her chart say about her communication style?',
    "What career paths or aspirations are suggested by my wife's astrological chart?",
    "What talents and abilities are highlighted in my wife's astrological chart? How can I support her in developing these talents?",
    'How does my wife interact with others? What does her chart say about her social skills and friendships?',
    "What does my wife's astrological chart indicate about our relationship dynamics and compatibility?",
    "What does my wife's astrological chart indicate about her physical and mental health? Are there any areas I should pay particular attention to?",
    'How does my wife handle conflicts? What strategies can we use to resolve conflicts effectively according to her astrological chart?',
    "What does my wife's astrological chart reveal about her financial habits and approach to money management?",
    'What hobbies and interests are likely to appeal to my wife according to her astrological chart?',
    "What does my wife's astrological chart reveal about her potential for spiritual and personal growth?",
    "What future predictions can be made about my wife's life based on her astrological chart?",
    'How does my wife relate to her family? What can her chart tell me about her family dynamics and relationships?',
  ],
  'Know your colleague': [
    'What are the key personality traits of my colleague according to their astrological chart?',
    "What are the main strengths and weaknesses indicated in my colleague's astrological chart?",
    'How does my colleague prefer to communicate? What does their chart say about their communication style?',
    "What career aspirations and goals are suggested by my colleague's astrological chart?",
    "What talents and abilities are highlighted in my colleague's astrological chart? How can we leverage these in our team?",
    'How does my colleague interact with others? What does their chart say about their social skills and teamwork abilities?',
    "What does my colleague's astrological chart indicate about their approach to problem-solving and decision-making?",
    'How does my colleague handle stress and conflicts according to their astrological chart? What strategies can we use to support them?',
    "What does my colleague's astrological chart reveal about their motivation and work ethic?",
    "How can my colleague best contribute to our team's success based on their astrological chart?",
    "What does my colleague's astrological chart say about their potential for leadership and management?",
    "What are my colleague's preferred working styles and environments according to their astrological chart?",
    'How does my colleague approach innovation and creativity? What insights can we gain from their chart?',
    "What does my colleague's astrological chart reveal about their long-term career prospects and development?",
    'How can we improve our working relationship and collaboration based on astrological insights about my colleague?',
  ],
  'Know your boss': [
    'What are the key personality traits of my boss according to their astrological chart?',
    "What are the main strengths and weaknesses indicated in my boss's astrological chart?",
    'How does my boss prefer to communicate? What does their chart say about their communication style?',
    "What leadership qualities are highlighted in my boss's astrological chart?",
    'How does my boss handle decision-making and problem-solving according to their astrological chart?',
    'What motivates my boss, and how can I align my work with their motivations based on astrological insights?',
    'How does my boss handle stress and conflicts according to their astrological chart? What strategies can I use to support them?',
    "What does my boss's astrological chart reveal about their management and delegation style?",
    'How does my boss interact with the team, and what does their chart say about their social skills and teamwork abilities?',
    "What are my boss's long-term career goals and aspirations according to their astrological chart?",
    'How can I best communicate and collaborate with my boss based on their astrological chart?',
    "What does my boss's astrological chart indicate about their approach to innovation and creativity?",
    "How can I align my work to better meet my boss's expectations and goals according to their astrological chart?",
    "What does my boss's astrological chart reveal about their potential for growth and development in their role?",
    'How can I build a stronger working relationship with my boss based on astrological insights?',
  ],
  'Know your mother': [
    'What are the key personality traits of my mother according to her astrological chart?',
    "What are the main strengths and weaknesses indicated in my mother's astrological chart?",
    "What does my mother's astrological chart reveal about her emotional needs and how she expresses her emotions?",
    'How does my mother prefer to communicate? What does her chart say about her communication style?',
    "What career paths or aspirations are suggested by my mother's astrological chart?",
    "What talents and abilities are highlighted in my mother's astrological chart? How can I support her in developing these talents?",
    'How does my mother interact with others? What does her chart say about her social skills and friendships?',
    "What does my mother's astrological chart indicate about our relationship dynamics and compatibility?",
    "What does my mother's astrological chart indicate about her physical and mental health? Are there any areas I should pay particular attention to?",
    'How does my mother handle conflicts? What strategies can we use to resolve conflicts effectively according to her astrological chart?',
    "What does my mother's astrological chart reveal about her financial habits and approach to money management?",
    'What hobbies and interests are likely to appeal to my mother according to her astrological chart?',
    "What does my mother's astrological chart reveal about her potential for spiritual and personal growth?",
    "What future predictions can be made about my mother's life based on her astrological chart?",
    'How does my mother relate to her family? What can her chart tell me about her family dynamics and relationships?',
  ],
  'Know your friend': [
    'What are the key personality traits of my friend according to their astrological chart?',
    "What are the main strengths and weaknesses indicated in my friend's astrological chart?",
    "What does my friend's astrological chart reveal about their emotional needs and how they express their emotions?",
    'How does my friend prefer to communicate? What does their chart say about their communication style?',
    "What career paths or aspirations are suggested by my friend's astrological chart?",
    "What talents and abilities are highlighted in my friend's astrological chart? How can I support them in developing these talents?",
    'How does my friend interact with others? What does their chart say about their social skills and friendships?',
    "What does my friend's astrological chart indicate about our relationship dynamics and compatibility?",
    "What does my friend's astrological chart indicate about their physical and mental health? Are there any areas I should pay particular attention to?",
    'How does my friend handle conflicts? What strategies can we use to resolve conflicts effectively according to their astrological chart?',
    "What does my friend's astrological chart reveal about their financial habits and approach to money management?",
    'What hobbies and interests are likely to appeal to my friend according to their astrological chart?',
    "What does my friend's astrological chart reveal about their potential for spiritual and personal growth?",
    "What future predictions can be made about my friend's life based on their astrological chart?",
    'How does my friend relate to their family? What can their chart tell me about their family dynamics and relationships?',
  ],

  'Know your guardian': [
    'What are the key personality traits of my guardian according to their astrological chart?',
    "What are the main strengths and weaknesses indicated in my guardian's astrological chart?",
    "What does my guardian's astrological chart reveal about their emotional needs and how they express their emotions?",
    'How does my guardian prefer to communicate? What does their chart say about their communication style?',
    "What career paths or aspirations are suggested by my guardian's astrological chart?",
    "What talents and abilities are highlighted in my guardian's astrological chart? How can I support them in developing these talents?",
    'How does my guardian interact with others? What does their chart say about their social skills and friendships?',
    "What does my guardian's astrological chart indicate about our relationship dynamics and compatibility?",
    "What does my guardian's astrological chart indicate about their physical and mental health? Are there any areas I should pay particular attention to?",
    'How does my guardian handle conflicts? What strategies can we use to resolve conflicts effectively according to their astrological chart?',
    "What does my guardian's astrological chart reveal about their financial habits and approach to money management?",
    'What hobbies and interests are likely to appeal to my guardian according to their astrological chart?',
    "What does my guardian's astrological chart reveal about their potential for spiritual and personal growth?",
    "What future predictions can be made about my guardian's life based on their astrological chart?",
    'How does my guardian relate to their family? What can their chart tell me about their family dynamics and relationships?',
  ],
};
